### ISSUE TITLE
[Feature Request] Improved Monitor Config Options

### ISSUE THREAD

**Issue by Tatertot5s** [AdyTech99/HealthIndicators#11]
**Is your feature request related to a problem? Please describe.**
When looking through the config, It's hard to find how to turn off the auto health monitor (idk what it's called, text that appears at top left when hitting entity.) The only way I could get it to dispensary was by setting *Attacked entities only* to false. This also seems like weird behavior too, I wouldn't expect for it to completely dissapear after turning that to false.

**Describe the solution you'd like**
Add a new option to disable the health monitor detecting entities you hit, completely separate from the attacked entities field. This could be in a separate tab, or just somewhere else in the advanced section. Additionally, make a slider for how long it should take dissapear after hitting a mob. (currently to my understanding is permanent.)

**Some Additional Notes**
The command "/healthindicators monitor-stop" or something like it would be useful for if your tracking a player and you want to stop having them be tracked.

Hopefully I'm not misunderstanding how this feature is supposed to work.

**Comment by AdyTech99** [comment]
[Fixed](https://modrinth.com/mod/health-indicators/version/21.1.3), you can now disable the indicator by running the command `/healthindicators stop-monitoring`
The monitoring showing up when hitting a mob is indeed a bug, that has also been fixed in the latest version
