### ISSUE TITLE
Toggleable Health/Armor [Feature Request]

### ISSUE THREAD

**Issue by SomeGDPerson123** [AdyTech99/HealthIndicators#12]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I think it would be cool to have an option to toggle the display of a mob's health or armor value.

**Describe alternatives you've considered**
nuh uh

**Additional context**
nuh uh

**Comment by SomeGDPerson123** [comment]
It's simple, yet it would make things better for me.

**Comment by AdyTech99** [comment]
You can already toggle the indicators on and off

**Comment by SomeGDPerson123** [comment]
No I mean like toggling them SEPERATELY. So like health on but armor off. Ya know what I'm saying?

**Comment by AdyTech99** [comment]
Yes, both health and armor already have separate toggles. You can disable the armor only by pressing your `right shift` button.

**Comment by SomeGDPerson123** [comment]
Oh...
