### ISSUE TITLE
Animated heart textures do not display animations

### ISSUE THREAD

**Issue by MadCow667** [AdyTech99/HealthIndicators#3]
I have a resource pack that changes the heart texture to a color-shifting rainbow. However, the animated hearts do not appear in the indicator as they do in the hot bar.
![2024-06-24_00 38 51](https://github.com/AdyTech99/HealthIndicators/assets/48391734/2dab1ca1-dd54-4f4e-893b-6c96718389fd)
![image](https://github.com/AdyTech99/HealthIndicators/assets/48391734/f6298f43-f32f-4ae8-8b51-3e25e74664f9)
(with zoom mod)
![image](https://github.com/AdyTech99/HealthIndicators/assets/48391734/97b16225-f95f-4863-b53a-99b5c6c83462)

For now the mod is still useful because I can simply use number display, but this would be great if it could be fixed. An option to return heart texture to vanilla in cases of breaking maybe?

**Comment by AdyTech99** [comment]
Hi, I believe I've successfully fixed the problem, but I'll need your exact texture pack to properly test it.

**Comment by MadCow667** [comment]
Okay, here it is.
[Rainbow HUD.zip](https://github.com/user-attachments/files/15981745/Rainbow.HUD.zip)

**Comment by AdyTech99** [comment]
Done. I added a new config option: "Use Vanilla Textures," all you have to do is enable it
https://modrinth.com/mod/health-indicators/version/3.2.0

**Comment by MadCow667** [comment]
I got it to work by using [MoreMcmeta](https://modrinth.com/mod/moremcmeta)
I used custom textures for the mod defined by using the vanilla heart override!
![working hearts](https://github.com/AdyTech99/HealthIndicators/assets/48391734/48488e67-7d35-4ba7-b70d-52f3c98a0a66)
[Rainbow Health Indicators.zip](https://github.com/user-attachments/files/16058899/Rainbow.Health.Indicators.zip)
I'm leaving the file here for reference incase anyone really wants to animate the health indicator as I have.
