### ISSUE TITLE
[Feature Request] Percentage Hearts

### ISSUE THREAD

**Issue by maevius669** [AdyTech99/HealthIndicators#4]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
an extra minimalistic option to have just 4 hearts as indicators with a 25% of health each

**Additional context**
instead of having hearts like this (even with a custom number per row):
`❤️❤️`
`❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️`

would it be possible to be just this:
`❤️❤️❤️❤️`
where every heart is a quarter of targets HP?

~~**another issue**
Also it would be convenient if "damaged_only" and "looking_at" respected the options from "passive_mobs" and "hostile_mobs", cause now it ignores it if for example "passive_mobs" is false.~~

**Comment by AdyTech99** [comment]
Thanks for the report. According to my tests, the "damaged_only" and "looking_at" options do respect the entity type filters for most mobs, except for some mobs like squids. Please confirm that is indeed what you are experiencing.

**Comment by maevius669** [comment]
Nevermind that issue. I'm sorry, it works as intended.

**Comment by AdyTech99** [comment]
> an extra minimalistic option to have just 4 hearts as indicators with a 25% of health each

Will work on this. Expect a new release within ~3 days.

**Comment by AdyTech99** [comment]
[Done](https://modrinth.com/mod/health-indicators/version/3.3.0)

**Comment by maevius669** [comment]
Thank you!
