### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zc1108aaa** [AdyTech99/HealthIndicators#5]
[crash-2024-06-26_19.41.55-client.txt](https://github.com/user-attachments/files/15987409/crash-2024-06-26_19.41.55-client.txt)

**Comment by AdyTech99** [comment]
Did you install [YetAnotherConfigLib](https://modrinth.com/mod/yacl)?

**Comment by zc1108aaa** [comment]
Installation
![image](https://github.com/AdyTech99/HealthIndicators/assets/155424398/0a0a6e17-9fd6-4717-b085-728cb9a88e10)

**Comment by Swaritz** [comment]
Make sure you have the latest version of YetAnotherConfigLib, and please provide a crash report after installing it so we can all come to a conclusion.

**Comment by AdyTech99** [comment]
Please answer the above question.
