### ISSUE TITLE
Armor Indicators

### ISSUE THREAD

**Issue by finnxv** [AdyTech99/HealthIndicators#6]
I don't know if it can be called an Issue, but I have no idea how to configure the Mod to only show HP Indicator, whenever Player has Armor equiped, their HP disapears and then their Armor Indicator shows up, is there any option to Disable it?

![2024-06-28_18 04 16_edited](https://github.com/AdyTech99/HealthIndicators/assets/107765970/ce1ce7e7-21bd-41c4-ab5a-713bc972dbbf)

**Comment by spinx-wq** [comment]
how do you fix this?????

**Comment by AdyTech99** [comment]
Press the keybinds.
Right shift toggles armor indicators on/off
Left arrow toggles health indicators on/off
